/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GranHotel_vistas;

import GranHotel_AccesoADatos.HuespedData;
import GranHotel_Entidades.Huesped;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class AgregarHuesped extends javax.swing.JInternalFrame {   
FondoPanel fondo=new FondoPanel();
    /**
     * Creates new form AgregarHuesped
     */
    public AgregarHuesped() {
       this.setContentPane(fondo);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPanel2();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Jnombre = new javax.swing.JTextField();
        Japellido = new javax.swing.JTextField();
        Jdni = new javax.swing.JTextField();
        Jnumero = new javax.swing.JTextField();
        Jdomi = new javax.swing.JTextField();
        Jcorreo = new javax.swing.JTextField();
        Jestado = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        Limpiar = new javax.swing.JButton();
        texto = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName(""); // NOI18N

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/circulo-de-usuario.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellido");

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Correo");

        jLabel5.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Numero Telefonico");

        jLabel7.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Dni");

        jLabel8.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Domicilio");

        jLabel6.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estado(true/else)");

        Jnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JnombreKeyReleased(evt);
            }
        });

        Japellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JapellidoKeyReleased(evt);
            }
        });

        Jdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JdniKeyReleased(evt);
            }
        });

        Jnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JnumeroActionPerformed(evt);
            }
        });
        Jnumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JnumeroKeyReleased(evt);
            }
        });

        Jdomi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JdomiKeyReleased(evt);
            }
        });

        Jcorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JcorreoKeyReleased(evt);
            }
        });

        Jestado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                JestadoKeyReleased(evt);
            }
        });

        boton.setBackground(new java.awt.Color(0, 204, 204));
        boton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        boton.setText("Registrar");
        boton.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton.setEnabled(false);
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        Limpiar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        Limpiar.setText("Limpiar");
        Limpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        texto.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        texto.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(Jnumero, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(Jnombre)
                            .addComponent(Jdni, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Japellido)
                            .addComponent(Jdomi)
                            .addComponent(Jcorreo)
                            .addComponent(Jestado))
                        .addGap(18, 18, 18)
                        .addComponent(texto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(boton)
                        .addGap(18, 18, 18)
                        .addComponent(Limpiar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(3, 3, 3)
                .addComponent(Japellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jdomi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(texto))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Jestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton)
                    .addComponent(Limpiar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(704, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JnumeroActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
HuespedData hues=new HuespedData();
Huesped huesped=new Huesped();



huesped.setNombre(Jnombre.getText());
huesped.setApellido(Japellido.getText());
huesped.setDni(Integer.parseInt(Jdni.getText()));

huesped.setCelular(Integer.parseInt((Jnumero.getText())));

huesped.setDomicilio(Jdomi.getText());
huesped.setCorreo(Jcorreo.getText());
huesped.setActivo(Boolean.valueOf(Jestado.getText()));

hues.guardarHuesped(huesped);
limpiar();

    }//GEN-LAST:event_botonActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed
     limpiar();
    }//GEN-LAST:event_LimpiarActionPerformed

    private void JnombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JnombreKeyReleased
     
        validacion(evt);
        Liberar();
        
  
     
      
    }//GEN-LAST:event_JnombreKeyReleased

    private void JapellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JapellidoKeyReleased

        validacion(evt);
        Liberar();
      
        
    }//GEN-LAST:event_JapellidoKeyReleased

    private void JdniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JdniKeyReleased

         
Numer(evt);
if(Jdni.getText().length()==8){
    Jdni.setEditable(false);
    Jdni.setEnabled(false);
    Liberar();
    
    
}
    }//GEN-LAST:event_JdniKeyReleased

    private void JnumeroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JnumeroKeyReleased


Numer(evt);
Liberar();
if(Jnumero.getText().length()==10){
Jnumero.setEditable(false);
Jnumero.setEnabled(false);
}
    }//GEN-LAST:event_JnumeroKeyReleased

    private void JdomiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JdomiKeyReleased

  
Liberar(); 



    }//GEN-LAST:event_JdomiKeyReleased

    private void JcorreoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JcorreoKeyReleased


Correo(evt);
Liberar();

        
    }//GEN-LAST:event_JcorreoKeyReleased

    private void JestadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JestadoKeyReleased

validacion(evt);

        if (Jestado.getText().length() == 4) {
            if (Jestado.getText() == "true" || Jestado.getText() == "TRUE" || Jestado.getText() == "else" || Jestado.getText() == "ELSE") {

              JOptionPane.showMessageDialog(this, "INGRESE TRUE O ELSE");
                Jestado.setText("");
                  Liberar();
               
            }else
                
                Jestado.setEditable(false);
                Jestado.setEnabled(false);
                boton.setEnabled(true);
                        }
            
        
    
                     

    }//GEN-LAST:event_JestadoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Japellido;
    private javax.swing.JTextField Jcorreo;
    private javax.swing.JTextField Jdni;
    private javax.swing.JTextField Jdomi;
    private javax.swing.JTextField Jestado;
    private javax.swing.JTextField Jnombre;
    private javax.swing.JTextField Jnumero;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton boton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel texto;
    // End of variables declaration//GEN-END:variables
class FondoPanel extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen=new ImageIcon(getClass().getResource("/Imagenes/background.jpg")).getImage();
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
}
class FondoPanel2 extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen=new ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg")).getImage();
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
}

private void limpiar(){
     Japellido.setText("");
     Jcorreo.setText("");
     Jdni.setText("");
     Jdomi.setText("");
     Jestado.setText("");
     Jnombre.setText("");
     Jnumero.setText("");
     
     boton.setEnabled(false);
     Jestado.setEditable(true);
     Jdni.setEditable(true);
     Jdni.setEnabled(true);
     Jnumero.setEditable(true);
     Jnumero.setEnabled(true);
     Jestado.setEditable(true);
     Jestado.setEnabled(true);
     
     
     
     


}

public void validacion(java.awt.event.KeyEvent evento){
    
//codigo para verificar caracteres 
    if(evento.getKeyChar()>=33 && evento.getKeyChar()<=64 
            || evento.getKeyChar()>=91 && evento.getKeyChar()<=96
            || evento.getKeyChar()>=123 && evento.getKeyChar()<=208){
        
        evento.consume();
        JOptionPane.showMessageDialog(this, "NO SE PERMITEN CARACTERES ESPECIALES");
        limpiar();
        
    }
      
    }
 public void CampoVacio(java.awt.event.KeyEvent evento){
     if(Jnombre.getText().isEmpty()||Japellido.getText().isEmpty()||Japellido.getText().isEmpty()
    ||Jdni.getText().isEmpty()||Jdomi.getText().isEmpty()
     ||Jestado.getText().isEmpty()||Jnombre.getText().isEmpty()||Jnumero.getText().isEmpty()){
         
         if(!Jcorreo.getText().contains("@")||!Jcorreo.getText().contains(".com")){
             texto.setText("DEBE CONTENER @ Y .COM");
         
         JOptionPane.showMessageDialog(this,"DEBE LLERNAR TODOS LOS CAMPOS");
         limpiar();
     }
         else
             boton.setEnabled(true);
     }
 }
public void Correo(java.awt.event.KeyEvent evento){
     if(evento.getKeyChar()>=32 && evento.getKeyChar()<=44 
             || evento.getKeyChar()==47
             || evento.getKeyChar()>=58&&evento.getKeyChar()<=63
             || evento.getKeyChar()>=91&&evento.getKeyChar()<=94
             || evento.getKeyChar()==96
             || evento.getKeyChar()>=123 &&evento.getKeyChar()<=255){
         evento.consume();
         JOptionPane.showMessageDialog(this,"NO SE PERMITE ESE CARACTER");
         limpiar();
     }
 
           
}

public void Numer(java.awt.event.KeyEvent evento){
    
   if(evento.getKeyChar()>=32&&evento.getKeyChar()<=47
            || evento.getKeyChar() >= 58 && evento.getKeyChar() <= 255) {
        evento.consume();
        JOptionPane.showMessageDialog(this, "INGRESE SOLO NUMEROS,SIN SIMBOLOS");
        limpiar();
        
   }
    
}
public void Liberar(){
    if(!Jnombre.getText().isEmpty()&&!Japellido.getText().isEmpty()&&!Japellido.getText().isEmpty()
    &&!Jdni.getText().isEmpty()&&!Jdomi.getText().isEmpty()
     &&!Jestado.getText().isEmpty()&&!Jnombre.getText().isEmpty()&&!Jnumero.getText().isEmpty()){
        if(Jdni.getText().length()<=8&&Jdni.getText().length()>=0){
        boton.setEnabled(true);
        }
        
    }
    if(!Jnombre.getText().isEmpty()&&!Japellido.getText().isEmpty()&&!Japellido.getText().isEmpty()
    &&!Jdni.getText().isEmpty()&&!Jdomi.getText().isEmpty()
     &&!Jestado.getText().isEmpty()&&!Jnombre.getText().isEmpty()&&!Jnumero.getText().isEmpty()){
        if(Jdni.getText().length()<=8&&Jdni.getText().length()>=0){
        boton.setEnabled(true);
        }
        

    }
}
}






