/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GranHotel_vistas;

import GranHotel_AccesoADatos.TipoHabitacionData;
import GranHotel_Entidades.TipoCama;
import GranHotel_Entidades.TipoHabitacion;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Usuario
 */
public class AgregarTipoHabitacion extends javax.swing.JInternalFrame {
    FondoPanel fondo=new FondoPanel();

    /**
     * Creates new form AgregarTipoHabitacion
     */
    public AgregarTipoHabitacion() {
        this.setContentPane(fondo);
        
        initComponents();
       rellenarcombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        max = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cantcamas = new javax.swing.JTextField();
        asd = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        boton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 0));
        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(0, 0));
        setName(""); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Maximo De Personas");

        max.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxActionPerformed(evt);
            }
        });
        max.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                maxKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad De Camas");

        cantcamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantcamasActionPerformed(evt);
            }
        });
        cantcamas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cantcamasKeyReleased(evt);
            }
        });

        asd.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        asd.setForeground(new java.awt.Color(255, 255, 255));
        asd.setText("Tipo De Cama");

        combo.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        combo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        combo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel4.setFont(new java.awt.Font("Roboto Light", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio");

        precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                precioKeyReleased(evt);
            }
        });

        boton.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        boton.setText("Agregar");
        boton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        boton.setEnabled(false);
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jButton2.setText("Limpiar");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(asd)
                        .addComponent(max)
                        .addComponent(jLabel1)
                        .addComponent(cantcamas, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cantcamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(asd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cantcamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantcamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantcamasActionPerformed

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        TipoHabitacionData tipocama = new TipoHabitacionData();
        TipoHabitacion habitacion = new TipoHabitacion();

        habitacion.setCantCamas(Integer.parseInt(cantcamas.getText()));
        habitacion.setMaxPersonas(Integer.parseInt(max.getText()));
        habitacion.setTipoDeCama((TipoCama) combo.getSelectedItem());
        habitacion.setPrecio(Integer.parseInt(precio.getText()));

        tipocama.guardarTipoHabitacion(habitacion);
        limpiar();


    }//GEN-LAST:event_botonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
limpiar();     
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void maxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxActionPerformed

    private void maxKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_maxKeyReleased


VeriNum(evt);

if(Integer.parseInt(max.getText())>=1&&Integer.parseInt(max.getText())<=8){
        max.setEnabled(false);
}else 
    if(Integer.parseInt(max.getText())<0||Integer.parseInt(max.getText())>9){
        JOptionPane.showMessageDialog(this, "NO SE PERMITE ESA CANTIDAD DE PERSONAS");
        JOptionPane.showMessageDialog(this, "DEBE INGRESAR ENTRE 1 A 8 PERSONAS");
        max.setText("");
    }else
        if(max.getText().length()>1){
        JOptionPane.showMessageDialog(this, "DEBE INGRESAR UN CARACTER");
        max.setText("");
        }
   //CODIGO PARA VERIFICAR CAMPOS VACIOS
if(!max.getText().isEmpty()&&!cantcamas.getText().isEmpty()&&!precio.getText().isEmpty()){
    boton.setEnabled(true);
}
   
    
    
    
    }//GEN-LAST:event_maxKeyReleased

    private void cantcamasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cantcamasKeyReleased
VeriNum(evt);
if(Integer.parseInt(cantcamas.getText())<1||Integer.parseInt(cantcamas.getText())>4){
    JOptionPane.showMessageDialog(this, "DEBE INGRESAR ENTRE 1 A 4 CAMAS");
    cantcamas.setText("");
}else
    if(cantcamas.getText().length()>1){
        JOptionPane.showMessageDialog(this, "DEBE INGRESAR 1 SOLO CARACTER NUMERICO");
        cantcamas.setText("");
    }else
        cantcamas.setEnabled(false);

//CODIGO PARA VERIFICAR CAMPOS VACIOS
if(!max.getText().isEmpty()&&!cantcamas.getText().isEmpty()&&!precio.getText().isEmpty()){
    boton.setEnabled(true);
}
    }//GEN-LAST:event_cantcamasKeyReleased

    private void precioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_precioKeyReleased
VeriNum(evt);
//prueba

if(precio.getText().length()>5){
    JOptionPane.showMessageDialog(this, "DEBE INGRESAR UN NUMERO MENOR A 5 CARACTERES");
    precio.setText("");
    boton.setEnabled(false);
}
//CODIGO PARA VERIFICAR CAMPOS VACIOS
if(!max.getText().isEmpty()&&!cantcamas.getText().isEmpty()&&!precio.getText().isEmpty()){
    boton.setEnabled(true);
}
    }//GEN-LAST:event_precioKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asd;
    private javax.swing.JButton boton;
    private javax.swing.JTextField cantcamas;
    private javax.swing.JComboBox<TipoCama> combo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField max;
    private javax.swing.JTextField precio;
    // End of variables declaration//GEN-END:variables

    class FondoPanel extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen=new ImageIcon(getClass().getResource("/Imagenes/habitacion.jpg")).getImage();
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
}
    class FondoPanel2 extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen=new ImageIcon(getClass().getResource("/Imagenes/fondo1.jpg")).getImage();
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
}
    
    
    
private void limpiar(){
    max.setText("");
    cantcamas.setText("");
    precio.setText("");
    
    max.setEnabled(true);
    max.setEditable(true);
    cantcamas.setEnabled(true);
    cantcamas.setEditable(true);
    precio.setEnabled(true);
    precio.setEditable(true);
    boton.setEnabled(false);
}



private void VeriNum(java.awt.event.KeyEvent evento){    
   if(evento.getKeyChar()>=32&&evento.getKeyChar()<=47
            || evento.getKeyChar() >= 58 && evento.getKeyChar() <= 255) {
        evento.consume();
        JOptionPane.showMessageDialog(this, "INGRESE SOLO NUMEROS,SIN SIMBOLOS");
        
        
   }
}

public void rellenarcombo(){
  combo.addItem(TipoCama.KING_SIZE);
  combo.addItem(TipoCama.QUEEN);
  combo.addItem(TipoCama.SIMPLE);
}

    
    
    

    
    
    
    


}
