/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GranHotel_vistas;

import GranHotel_AccesoADatos.HuespedData;
import GranHotel_Entidades.Huesped;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class HistorialHuesped extends javax.swing.JInternalFrame {
    FondoPanel fondo=new FondoPanel();
    int huesSelec;
    private DefaultTableModel modelo = new DefaultTableModel(){
        public boolean isCellEditable(int f, int c){
            return false;
        }
    };

    /**
     * Creates new form HistorialHuesped
     */
    public HistorialHuesped() {
        this.setContentPane(fondo);
        initComponents();
        armarCabecera();
        HuespedData hd = new HuespedData();
        for(Huesped hues: hd.listarHistorialDeHuespedes()){
            
            modelo.addRow(new Object[]{
                hues.getApellido(),
                hues.getNombre(),
                hues.getDni(),
                (hues.isActivo() ? "Si" : "No")
            });
        }
        deshabilitarBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtHuespedes = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtApellido = new javax.swing.JTextField();
        jbBajaHuesped = new javax.swing.JButton();
        jbAltaHuesped = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ingrese Nro DNI:");

        jtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtDniKeyReleased(evt);
            }
        });

        jtHuespedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Apellido", "Nombre", "Dni", "Activo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtHuespedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtHuespedesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtHuespedes);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Historial de Huespedes");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ingrese Apellido:");

        jtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtApellidoKeyReleased(evt);
            }
        });

        jbBajaHuesped.setText("Baja Huesped");
        jbBajaHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaHuespedActionPerformed(evt);
            }
        });

        jbAltaHuesped.setText("Alta Huesped");
        jbAltaHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaHuespedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jtDni))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(151, 151, 151)
                                .addComponent(jtApellido))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 102, Short.MAX_VALUE)
                .addComponent(jbAltaHuesped)
                .addGap(53, 53, 53)
                .addComponent(jbBajaHuesped)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbBajaHuesped)
                    .addComponent(jbAltaHuesped))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtDniKeyReleased
        // TODO add your handling code here:
        
        jtApellido.setText("");
        HuespedData hd = new HuespedData();
        borrarFilas();
        deshabilitarBotones();
        
        for(Huesped hues: hd.listarHistorialDeHuespedes()){
            
            if(String.valueOf(hues.getDni()).startsWith(jtDni.getText())){
                
                modelo.addRow(new Object[]{
                    hues.getApellido(),
                    hues.getNombre(),
                    hues.getDni(),
                    (hues.isActivo() ? "Si" : "No") 
                });
                
            }
        }
    }//GEN-LAST:event_jtDniKeyReleased

    private void jtApellidoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtApellidoKeyReleased
        // TODO add your handling code here:
        
        jtDni.setText("");
        HuespedData hd = new HuespedData();
        borrarFilas();
        deshabilitarBotones();
        
        for(Huesped hues: hd.listarHistorialDeHuespedes()){
            
            if(hues.getApellido().startsWith(jtApellido.getText())){
                
                modelo.addRow(new Object[]{
                    hues.getApellido(),
                    hues.getNombre(),
                    hues.getDni(),
                    (hues.isActivo() ? "Si" : "No")
                });
                
            }
        }
    }//GEN-LAST:event_jtApellidoKeyReleased

    private void jtHuespedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtHuespedesMouseClicked
        // TODO add your handling code here:
        
        huesSelec = Integer.valueOf(jtHuespedes.getValueAt(jtHuespedes.getSelectedRow(), 2).toString());
        HuespedData hd = new HuespedData();
        if(hd.buscarHuespedPorDni(huesSelec).isActivo()){
            jbBajaHuesped.setEnabled(true);
            jbAltaHuesped.setEnabled(false);
            
        }else{
            jbAltaHuesped.setEnabled(true);
            jbBajaHuesped.setEnabled(false);
        }
        
    }//GEN-LAST:event_jtHuespedesMouseClicked

    private void jbBajaHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaHuespedActionPerformed
        // TODO add your handling code here:
        
        HuespedData hd = new HuespedData();
        hd.bajaHuesped(huesSelec);
        
    }//GEN-LAST:event_jbBajaHuespedActionPerformed

    private void jbAltaHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaHuespedActionPerformed
        // TODO add your handling code here:
        HuespedData hd = new HuespedData();
        hd.altaHuesped(huesSelec);
        
    }//GEN-LAST:event_jbAltaHuespedActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAltaHuesped;
    private javax.swing.JButton jbBajaHuesped;
    private javax.swing.JTextField jtApellido;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTable jtHuespedes;
    // End of variables declaration//GEN-END:variables

    private void deshabilitarBotones(){
        
        huesSelec = -1;
        jbAltaHuesped.setEnabled(false);
        jbBajaHuesped.setEnabled(false);
        
    }
    
    private void armarCabecera(){
        
        modelo.addColumn("Apellido");
        modelo.addColumn("Nombre");
        modelo.addColumn("Documento");
        modelo.addColumn("Activo");
        jtHuespedes.setModel(modelo);
        
    }
    
    private void borrarFilas(){
        
        for(int filas = jtHuespedes.getRowCount()-1; filas >= 0 ; filas--){
            modelo.removeRow(filas);
        }
        
    }
    
class FondoPanel extends JPanel{
    private Image imagen;
    @Override
    public void paint(Graphics g){
        imagen=new ImageIcon(getClass().getResource("/Imagenes/hotel5.jpg")).getImage();
        g.drawImage(imagen,0,0,getWidth(),getHeight(),this);
        setOpaque(false);
        super.paint(g);
    }
}

}
